"""
DESCRIPTION:

    Visualizes and exports proof trees generated by the backward chainer.
    Creates both text-based and graphical representations showing:
    - The complete proof tree structure
    - Variable substitutions at each step
    - Individual generation
    - Rule applications

USAGE:

    python visualizer.py --ontology-path data/family.ttl --output-dir output/

AUTHOR:

    Vincent Van Schependom
"""

import argparse
import os
import sys
from typing import Dict, List, Set, Optional, Tuple
from collections import defaultdict

# For graph visualization
try:
    import graphviz

    HAS_GRAPHVIZ = True
except ImportError:
    HAS_GRAPHVIZ = False
    print("Warning: graphviz not installed. Install with: pip install graphviz")

# Custom imports
from data_structures import (
    Proof,
    Atom,
    ExecutableRule,
    Var,
    Individual,
    Class,
    Relation,
)
from parser import OntologyParser
from chainer import BackwardChainer
from rdflib.namespace import RDF


class ProofTreeVisualizer:
    """
    Visualizes proof trees in multiple formats:
    - Text-based hierarchical view
    - DOT/Graphviz graph
    - JSON export
    """

    def __init__(self, output_dir: str = "output"):
        """
        Initialize the visualizer.

        Args:
            output_dir: Directory to save output files
        """
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

        # Track nodes for graphviz
        self.node_counter = 0
        self.node_ids: Dict[Proof, str] = {}

    def visualize_all_proofs(
        self,
        chainer: BackwardChainer,
        rule_names: Optional[List[str]] = None,
        max_proofs_per_rule: int = 5,
    ) -> None:
        """
        Generate visualizations for all rules (or specified rules).

        Args:
            chainer: The BackwardChainer instance
            rule_names: List of rule names to visualize (None = all rules)
            max_proofs_per_rule: Maximum number of proof trees to visualize per rule
        """
        if rule_names is None:
            rule_names = list(chainer.all_rules.keys())

        print(f"\n{'=' * 80}")
        print(f"VISUALIZING PROOF TREES")
        print(f"{'=' * 80}")

        for rule_name in rule_names:
            if rule_name not in chainer.all_rules:
                print(f"\nWarning: Rule '{rule_name}' not found. Skipping.")
                continue

            print(f"\n{'-' * 80}")
            print(f"Rule: {rule_name}")
            print(f"{'-' * 80}")

            # Generate proofs
            proof_generator = chainer.generate_proof_trees(rule_name)
            proofs = []

            try:
                for i, proof in enumerate(proof_generator):
                    if i >= max_proofs_per_rule:
                        print(
                            f"\nReached max proofs limit ({max_proofs_per_rule}). Stopping generation."
                        )
                        break
                    proofs.append(proof)

            except Exception as e:
                print(f"\nError generating proofs for {rule_name}: {e}")
                import traceback

                traceback.print_exc()
                continue

            if not proofs:
                print(f"No proofs generated for rule: {rule_name}")
                continue

            print(f"\nGenerated {len(proofs)} proof tree(s) for rule: {rule_name}")

            # Visualize each proof
            for i, proof in enumerate(proofs):
                proof_id = f"{rule_name}_proof_{i + 1}"
                print(f"\n--- Proof Tree {i + 1}/{len(proofs)} ---")

                # Text visualization
                self.print_proof_tree_text(proof)

                # Save text to file
                text_file = os.path.join(self.output_dir, f"{proof_id}.txt")
                with open(text_file, "w") as f:
                    f.write(f"Proof Tree for Rule: {rule_name}\n")
                    f.write(f"{'=' * 80}\n\n")
                    f.write(self.get_proof_tree_text(proof))
                print(f"✓ Saved text visualization to: {text_file}")

                # Graphviz visualization
                if HAS_GRAPHVIZ:
                    self.create_graphviz_visualization(proof, proof_id)

                # Statistics
                stats = self.get_proof_statistics(proof)
                print(f"\nProof Statistics:")
                print(f"  Total nodes: {stats['total_nodes']}")
                print(f"  Base facts: {stats['base_facts']}")
                print(f"  Derived facts: {stats['derived_facts']}")
                print(f"  Max depth: {stats['max_depth']}")
                print(f"  Unique individuals: {stats['unique_individuals']}")
                print(f"  Rules used: {', '.join(stats['rules_used'])}")

    def print_proof_tree_text(self, proof: Proof, indent: int = 0) -> None:
        """
        Print proof tree in hierarchical text format to console.

        Args:
            proof: The proof tree to print
            indent: Current indentation level
        """
        prefix = "  " * indent

        # Print the goal
        goal_str = self._format_atom(proof.goal)
        if proof.rule is None:
            print(f"{prefix}[BASE FACT] {goal_str}")
        else:
            print(f"{prefix}[DERIVE] {goal_str}")
            print(f"{prefix}  via rule: {proof.rule.name}")

            # Show variable substitutions if we can infer them
            if proof.sub_proofs:
                print(f"{prefix}  from premises:")
                for sub_proof in proof.sub_proofs:
                    self.print_proof_tree_text(sub_proof, indent + 2)

    def get_proof_tree_text(self, proof: Proof, indent: int = 0) -> str:
        """
        Get proof tree as formatted text string.

        Args:
            proof: The proof tree
            indent: Current indentation level

        Returns:
            Formatted string representation
        """
        lines = []
        prefix = "  " * indent

        # Format the goal
        goal_str = self._format_atom(proof.goal)

        if proof.rule is None:
            lines.append(f"{prefix}[BASE FACT] {goal_str}")
        else:
            lines.append(f"{prefix}[DERIVE] {goal_str}")
            lines.append(f"{prefix}  via rule: {proof.rule.name}")

            # Show recursion info if applicable
            if proof.recursive_use_counts:
                counts_str = ", ".join(
                    [f"{name}:{count}" for name, count in proof.recursive_use_counts]
                )
                lines.append(f"{prefix}  recursion: {counts_str}")

            if proof.sub_proofs:
                lines.append(f"{prefix}  from premises:")
                for sub_proof in proof.sub_proofs:
                    lines.append(self.get_proof_tree_text(sub_proof, indent + 2))

        return "\n".join(lines)

    def create_graphviz_visualization(self, proof: Proof, proof_id: str) -> None:
        """
        Create a Graphviz visualization of the proof tree.

        Args:
            proof: The proof tree
            proof_id: Identifier for this proof (used in filename)
        """
        # Reset node tracking
        self.node_counter = 0
        self.node_ids = {}

        # Create graph
        dot = graphviz.Digraph(comment=f"Proof Tree: {proof_id}")
        dot.attr(rankdir="TB")  # Top to bottom
        dot.attr("node", shape="box", style="rounded")

        # Build the graph
        self._add_proof_to_graph(proof, dot, None)

        # Save
        output_path = os.path.join(self.output_dir, proof_id)
        try:
            dot.render(output_path, format="pdf", cleanup=True)
            print(f"✓ Saved graph visualization to: {output_path}.pdf")
        except Exception as e:
            print(f"✗ Failed to create graph: {e}")
            # Save dot file anyway
            dot.save(output_path + ".dot")
            print(f"  Saved .dot file to: {output_path}.dot")

    def _add_proof_to_graph(
        self, proof: Proof, dot: graphviz.Digraph, parent_id: Optional[str]
    ) -> str:
        """
        Recursively add proof nodes to graphviz graph.

        Args:
            proof: Current proof node
            dot: Graphviz graph object
            parent_id: ID of parent node (None for root)

        Returns:
            Node ID for this proof
        """
        # Get or create node ID
        if proof in self.node_ids:
            return self.node_ids[proof]

        node_id = f"node_{self.node_counter}"
        self.node_counter += 1
        self.node_ids[proof] = node_id

        # Format node label
        goal_str = self._format_atom(proof.goal)

        if proof.rule is None:
            # Base fact - green box
            label = f"BASE FACT\\n{goal_str}"
            dot.node(node_id, label, fillcolor="lightgreen", style="filled,rounded")
        else:
            # Derived fact - blue box
            label = f"DERIVE\\n{goal_str}\\n\\nRule: {proof.rule.name}"

            # Add recursion info if present
            if proof.recursive_use_counts:
                rec_info = ", ".join(
                    [f"{name}:{count}" for name, count in proof.recursive_use_counts]
                )
                label += f"\\nRecursion: {rec_info}"

            dot.node(node_id, label, fillcolor="lightblue", style="filled,rounded")

            # Add edges to sub-proofs
            for i, sub_proof in enumerate(proof.sub_proofs):
                sub_id = self._add_proof_to_graph(sub_proof, dot, node_id)
                dot.edge(node_id, sub_id, label=f"premise {i + 1}")

        return node_id

    def _format_atom(self, atom: Atom) -> str:
        """Format an atom for display."""
        s = self._format_term(atom.subject)
        p = self._format_term(atom.predicate)
        o = self._format_term(atom.object)
        return f"({s}, {p}, {o})"

    def _format_term(self, term) -> str:
        """Format a term (Individual, Class, Relation, etc.) for display."""
        if isinstance(term, (Individual, Class, Relation)):
            return term.name
        elif isinstance(term, Var):
            return f"{term.name}"
        elif term == RDF.type:
            return "rdf:type"
        else:
            return str(term)

    def get_proof_statistics(self, proof: Proof) -> Dict:
        """
        Calculate statistics about a proof tree.

        Args:
            proof: The proof tree

        Returns:
            Dictionary of statistics
        """
        stats = {
            "total_nodes": 0,
            "base_facts": 0,
            "derived_facts": 0,
            "max_depth": 0,
            "unique_individuals": set(),
            "rules_used": set(),
        }

        def traverse(p: Proof, depth: int):
            stats["total_nodes"] += 1
            stats["max_depth"] = max(stats["max_depth"], depth)

            if p.rule is None:
                stats["base_facts"] += 1
            else:
                stats["derived_facts"] += 1
                stats["rules_used"].add(p.rule.name)

            # Collect individuals from goal
            for term in [p.goal.subject, p.goal.object]:
                if isinstance(term, Individual):
                    stats["unique_individuals"].add(term.name)

            # Recurse
            for sub in p.sub_proofs:
                traverse(sub, depth + 1)

        traverse(proof, 0)
        stats["unique_individuals"] = len(stats["unique_individuals"])
        stats["rules_used"] = sorted(list(stats["rules_used"]))

        return stats


def main():
    """Main entry point."""

    # Parse arguments
    parser = argparse.ArgumentParser(
        description="Visualize proof trees from backward chaining"
    )
    parser.add_argument(
        "--ontology-path",
        type=str,
        default="data/family.ttl",
        help="Path to the ontology file",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="output",
        help="Directory to save visualizations",
    )
    parser.add_argument(
        "--max-recursion", type=int, default=2, help="Maximum recursion depth"
    )
    parser.add_argument(
        "--max-proofs",
        type=int,
        default=5,
        help="Maximum number of proofs to visualize per rule",
    )
    parser.add_argument(
        "--rules",
        type=str,
        nargs="+",
        default=None,
        help="Specific rule names to visualize (default: all rules)",
    )

    args = parser.parse_args()

    # Check graphviz
    if not HAS_GRAPHVIZ:
        print("\n" + "!" * 80)
        print("WARNING: graphviz not installed. Only text output will be available.")
        print("Install with: pip install graphviz")
        print("You also need graphviz system package: https://graphviz.org/download/")
        print("!" * 80 + "\n")

    try:
        # Parse ontology
        print(f"Loading ontology from: {args.ontology_path}")
        onto_parser = OntologyParser(args.ontology_path)

        # Initialize chainer
        print(f"Initializing backward chainer (max recursion: {args.max_recursion})")
        chainer = BackwardChainer(
            all_rules=onto_parser.rules, max_recursion_depth=args.max_recursion
        )

        # Create visualizer
        visualizer = ProofTreeVisualizer(output_dir=args.output_dir)

        # Visualize proofs
        visualizer.visualize_all_proofs(
            chainer=chainer, rule_names=args.rules, max_proofs_per_rule=args.max_proofs
        )

        print(f"\n{'=' * 80}")
        print(f"VISUALIZATION COMPLETE")
        print(f"Output saved to: {args.output_dir}")
        print(f"{'=' * 80}\n")

    except FileNotFoundError:
        print(
            f"Error: Ontology file not found at '{args.ontology_path}'", file=sys.stderr
        )
        sys.exit(1)
    except Exception as e:
        print(f"\nAn unexpected error occurred:\n{e}", file=sys.stderr)
        import traceback

        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
